name: webview_flutter
description: WebOS implementation for webview_flutter
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    platforms:
      linux:
        default_package: webview_flutter_linux

dependencies:
  flutter:
    sdk: flutter

  webview_flutter_linux:
    path: ../webview_flutter_linux
  webview_flutter_platform_interface:
    path: ../webview_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
