name: webview_flutter_linux
description: Linux implementation of the webview_flutter plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      linux:
        pluginClass: WebviewFlutterPlugin
        dartPluginClass: WebviewFlutterLinux

dependencies:
  flutter:
    sdk: flutter

  webview_flutter_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
